config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "tweets#index"
  resources :users, only: [:edit, :update, :show]
  resources :tweets

  post 'like/:id' => 'likes#create', as: 'create_like'
  delete 'like/:id' => 'likes#destroy', as: 'destroy_like'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :tweet
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
  has_one_attached :image
  has_many :likes
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :tweets
  has_many :likes

  def liked_by?(tweet_id)
    likes.where(tweet_id: tweet_id).exists?
  end

  validates :nickname, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :basic_auth
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV["BASIC_AUTH_USER"] && password == ENV["BASIC_AUTH_PASSWORD"]
    end
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname, :stature, :body])
  end

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :tweet_params

 def create
   Like.create(user_id: current_user.id, tweet_id: params[:id])
 end
 
 def destroy
   Like.find_by(user_id: current_user.id, tweet_id: params[:id]).destroy
 end
 
 private
 
 def tweet_params
   @tweet = Tweet.find(params[:id])
 end
 
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController

  def index
    @tweets = Tweet.all.order('created_at DESC')
    @tweet = Tweet.where(user_id: current_user.id).last.weight
  end

  def new
    @tweet = Tweet.new
  end

  def create
    @tweet = Tweet.new(tweet_params)
    if @tweet.save
      redirect_to root_path
    else
      render :new
    end
  end

  private

  def tweet_params
    params.require(:tweet).permit(:image, :diary, :weight).merge(user_id: current_user.id)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @tweets = current_user.tweets
  end

  def edit
  end

  def update
    if current_user.update(user_params)
    redirect_to root_path
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:nickname, :email, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<%= favicon_link_tag 'favicon.png'%>
<html>
  <head>
    <title>chokomemo</title>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.13.0/css/all.css" integrity="sha384-Bfad6CLCknfcloXFOyFnlgtENryhrpZCe29RTifKEixXQZ38WheV+i/6YWSzkz3V" crossorigin="anonymous">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= javascript_include_tag "//www.google.com/jsapi" %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    
  </head>

  <body>
  <header class="header">
      <div class="header__bar row">
        <h1 class="grid-6"><a href="/">ChokoMemo</a></h1>
        <% if user_signed_in? %>
          <div class="grid-6">
                <%= link_to "Mypage", "/users/#{current_user.id}", class: "post" %>
                <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "post" %>
          </div>
        <% else %>
          <div class="grid-6">
            <%= link_to "Log in", new_user_session_path, class: "post" %>
            <%= link_to "新規登録", new_user_registration_path, class: "post" %>
          </div>
        <% end %>
      </div>
    </header>
    <%= yield %>
  </body>
</html>

app/views/likes/_like.html.erb
<% if user_signed_in? %>
 <% if current_user.liked_by?(tweet.id) %>
   <td>
     <%= link_to destroy_like_path(tweet), method: :DELETE, remote: true, data: {"turbolinks" => false} do %> 
       <i class="fa fa-heart unlike-btn"></i> 
     <% end %> 
     <%= tweet.likes.count %>
   </td>
 <% else %>
   <td>
     <%= link_to create_like_path(tweet), method: :POST, remote: true, data: {"turbolinks" => false} do %> 
       <i class="fa fa-heart like-btn"></i> 
     <% end %> 
     <%= tweet.likes.count %>
   </td>
 <% end %>
<% end %>

app/views/tweets/_main_page.html.erb
<div class="tweets">
<div class="bg"></div>
<div class="bg bg2"></div>
<div class="bg bg3"></div>
  <div class='item-contents'>
    <h2 class='title'>みんなの投稿</h2>
    <ul class='item-lists'>
      <% @tweets.each do |tweet| %>
        <article class='list'>
          <%= link_to "#" do %>
            <div class='item-img-content'>
              <figure>
                <%= image_tag tweet.image, class: 'item-img'%>
              </figure>
              <div class='tweet-user'>
                <%= tweet.user.nickname %>
              </div>
              <div class='tweet-time'>
                <%= tweet.created_at.strftime('%Y/%m/%d') %>
              </div>
              <div class='item-info'>
                <%= tweet.diary %>
              </div>
              <div id="likes_buttons_<%= tweet.id %>">
                <%= render partial: 'likes/like', locals: {tweet: tweet} %>
              </div>
            </div>
          <% end %>
        </article>
      <% end %>
    </ul>
  </div>
</div>

app/views/tweets/_side_bar.html.erb
<div class="rooms">
  <h1 class='name-text'>
      こんにちは
      <%= link_to current_user.nickname, edit_user_path(current_user), class: "name" %>
      さん
  </h1>
  <% if @tweet <= current_user.body %>
    <%= image_tag "cake3.png", class:"cake3" %>
    <% elsif @tweet <= current_user.body + 5 %>
    <%= image_tag "cake2.png", class:"cake2" %>
    <% else %>
    <%= image_tag "cake1.png", class:"cake1" %>
  <% end %>
  <h1 class='goal-text'>
      目標の体重
      <%= current_user.body %>
      kg
  </h1>
  <h1 class='goal-text'>
      現在の体重
      <%= @tweet %>
      kg
  </h1>
      <%= link_to "投稿する", new_tweet_path, class: "post-type" %>
</div>

app/views/tweets/index.html.erb
<div class="wrapper">
  <div class="side-bar">
    <%= render "side_bar" %>
  </div>
  <div class="page">
    <%= render "main_page" %>
  </div>
</div>

app/views/tweets/new.html.erb
<div class="contents row">
  <div class="container">
    <%= form_with(model: @tweet, local: true) do |form| %>
      <%= form.file_field :image, placeholder: "Image Url" %>
      今日の日記
      <%= form.text_area :diary, placeholder: "例：今日○○を食べて、通勤時に電車2駅分歩いた。", rows: "10" %>
      今日の体重
      <%= form.text_field :weight %>kg
      <%= form.submit "投稿する" %>
    <% end %>
  </div>
</div>

app/views/users/edit.html.erb
<div class='account-page' id='account-page'>
  <div class='account-page__inner clearfix'>
    <div class='account-page__inner--left account-page__header'>
      <h2>Edit Account</h2>
      <h5>アカウントの編集</h5>
      <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'btn'%>
      <%= link_to "トップページに戻る", root_path, class: 'btn'%>
    </div>
    <div class='account-page__inner--right user-form'>
      <%= form_with model: current_user, local: true do |f|%>
        <div class='field'>
          <div class='field-label'>
            <%= f.label :nickname%>
          </div>
          <div class='field-input'>
            <%= f.text_field :nickname, autofocus: true%>
          </div>
        </div>
        <div class='field'>
          <div class='field-label'>
            <%= f.label :目標体重%>
          </div>
          <div class='field-input'>
            <%= f.text_field :body, autofocus: true%>
          </div>
        </div>
        <div class='field'>
          <div class='field-label'>
            <%= f.label :email%>
          </div>
          <div class='field-input'>
            <%= f.email_field :email%>
          </div>
        </div>
        <div class='actions'>
          <%= f.submit "Update", class: 'btn'%>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="my-page">
<div class="my-page-title">
Mypage
</div>
<div class="back">
<div class="graph-title">
  これまでの体重
  </div>
  </div>
  <div class="graph">
    <%= line_chart @tweets.group_by_day(:created_at, format:"%m/%d", series: false).sum(:weight),
    height: "400px",
    min: 30,
    max: 80, 
    curve: false %>
  </div>
  </div>
  <div class="back">
<div class="graph-title">
  いままでの投稿
  </div>
  </div>
  <ul class='item-lists'>

    <% @tweets.each do |tweet| %>
      <li class='list'>
        <%= link_to '#' do %>
        <div class='item-img-content'>
          <div class='user-tweet-time'>
                <%= tweet.created_at.strftime('%Y/%m/%d') %>
              </div>
          <%= image_tag tweet.image, class: "user-item-img" %>
          <div class='user-item-info'>
                <%= tweet.diary %>
              </div>
          </div>
          <%end%>
          </li>
          <%end%>
          </ul>

</div>